2 курс 2 семестр/РПМ/django/firstproject/cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

2 курс 2 семестр/РПМ/django/firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from hello.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacti.html',contacti),
    path('',main_menu),
    path('main_menu.html',main_menu),
    path('arenda.html',arenda),
    path('o_nas.html',o_nas),
    path('pravila.html',pravila),
    path('create/', create_view),
    path('update/<int:id>', update_view),
    path('accounts/',include('django.contrib.auth.urls')),
    path('home/', include('hello.urls')),
    path('<int:id>/', comment_detail_view),
    path('delete/<int:id>/', delete_view),
    re_path(r'^cart/', include(('cart.urls','cart'), namespace='cart')),
    re_path('', include(('hello.urls', 'hello'), namespace='hello')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2 курс 2 семестр/РПМ/django/firstproject/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('room/', views.room_list, name='room_list'),
    path('<slug:category_slug>/', views.room_list, name='room_list_by_category'),
    path('<int:id>/<slug:slug>/', views.room_detail, name="room_detail")
]

2 курс 2 семестр/РПМ/django/firstproject/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('test/', views.send_order, name='test_send')
]

2 курс 2 семестр/РПМ/django/firstproject/cart/models.py
from django.db import models

# Create your models here.

2 курс 2 семестр/РПМ/django/firstproject/cart/forms.py
from django import forms
PRODUCT_QUANITY_CHOICES = [(i, str(i)) for i in range(1,21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

2 курс 2 семестр/РПМ/django/firstproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from hello.models import Room
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Room, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Room, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

2 курс 2 семестр/РПМ/django/firstproject/cart/templates/cart/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>
    <link rel="stylesheet" href="{% static 'style/main.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/main_ico.ico'%}" type="image/x-icon">
</head>
<body class="aut_body">
        <h1 class="text">Your shopping cart</h1>
        <div class="">
          <div class="">
            <div class="">
              <div class="">
                <div class="card">
                {% for item in cart %}
                    {% with product=item.product %}
                  <div class="">
                    <div class="">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="" src="{% if product.href_img %}{{ product.href_img.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}">
                        </a>
                    </div>
                    <div class="">
                      <div>
                        <p class="">Name</p>
                        <p class="">{{ product.name }}</p>
                      </div>
                    </div>
                    <div class="col-md-2 d-flex justify-content-center">
                      <div>
                        <p class="small text-muted mb-4 pb-2">Amount of hours</p>
                        <p class="lead fw-normal mb-0">{{ item.quantity }}</p>
                      </div>
                    </div>
                    <div class="col-md-2 d-flex justify-content-center">
                      <div>
                        <p class="small text-muted mb-4 pb-2">Price</p>
                        <p class="lead fw-normal mb-0">{{ item.price }} рублей</p>
                      </div>
                    </div>
                    <div class="col-md-2 d-flex justify-content-center">
                      <div>
                        <p class="small text-muted mb-4 pb-2">Total</p>
                        <p class="lead fw-normal mb-0">{{ item.total_price }} рублей</p>
                      </div>
                  </div>
                  <div class="col-md-2 d-flex justify-content-center">
                    <div>
                      <a href="{% url 'cart:cart_remove' product.id %}"><button class="newbutton">Remove</button></a>
                    </div>
                </div>
                  {% endwith %}
                {% endfor %}
                </div>
              </div>      
              <div class="d-flex justify-content-end">
                <a href="{% url 'hello:room_list' %}" type="button" class="btn btn-light btn-lg me-2"><button class="newbutton">Continue shopping</button></a>
                <a href="{% url 'orders:order_create' %}" type="button" class="btn btn-primary btn-lg"><button class="newbutton">Add to cart</button></a>
              </div>
            </div>
          </div>
        </div>
      </body>