2 курс 2 семестр/РПМ/django/firstproject/cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove')
]

2 курс 2 семестр/РПМ/django/firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from hello.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacti.html',contacti),
    path('',main_menu),
    path('main_menu.html',main_menu),
    path('arenda.html',arenda),
    path('o_nas.html',o_nas),
    path('pravila.html',pravila),
    path('create/', create_view),
    path('update/<int:id>', update_view),
    path('accounts/',include('django.contrib.auth.urls')),
    path('home/', include('hello.urls')),
    path('<int:id>/', comment_detail_view),
    path('delete/<int:id>/', delete_view),
    re_path(r'^cart/', include(('cart.urls','cart'), namespace='cart')),
    re_path('', include(('hello.urls', 'hello'), namespace='hello')),
    re_path(r'^orders/', include(('orders.urls', 'orders'), namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2 курс 2 семестр/РПМ/django/firstproject/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('test/', views.send_order, name='test_send')
]

2 курс 2 семестр/РПМ/django/firstproject/orders/models.py
from django.db import models
from hello.models import Room

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=25)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'Order {}'.format(self.id)
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Room, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return '{}'.format(self.id)
    def get_cost(self):
        return self.price * self.quantity

2 курс 2 семестр/РПМ/django/firstproject/orders/forms.py
from django import forms
from .models import *

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','email']

2 курс 2 семестр/РПМ/django/firstproject/orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from .forms import *
from .models import *
import sqlite3
from django.core.mail import send_mail
from django.conf import settings

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order=form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'],price=item['price'],quantity=item['quantity'])
            cart.clear()                 
            return render (request, 'orders/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/create.html',{'cart':cart, 'form':form})
def send_order(request):
    conn = sqlite3.connect('db.sqlite3')
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM \"orders_orderitem\"")
    rows = cursor.fetchall()
    subject = 'Заказ на сайте Кириешки'
    cursor.execute(f"SELECT * FROM \"orders_order\" WHERE id={rows[-1][3]}")
    rows2 = cursor.fetchall()
    order = rows2[0]
    cursor.execute(f"SELECT * FROM \"hello_room\" WHERE id={rows[-1][4]}")
    rows3 = cursor.fetchall()
    room = rows3[0]
    message = ''
    message += f"Здравствуйте, {order[1]} {order[2]}! Спасибо за заказ на нашем сайте! \nВаш заказ:\nНомер заказа: {rows[-1][0]}, Цена: {rows[-1][1]}, Номер товара: {rows[-1][4]}\nВы заказали: {room[1]} на {rows[-1][2]} часов\n"
    conn.close()
    send_mail(subject, message, settings.EMAIL_HOST_USER, ["nidhappy@mail.ru"])
    return render(request, 'orders/test.html')

2 курс 2 семестр/РПМ/django/firstproject/orders/templates/orders/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Оформление заказа</title>
    <link rel="stylesheet" href="{% static 'style/main.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/main_ico.ico'%}" type="image/x-icon">
</head>
<body class="aut_body">
<h1 class="text">Введите свои данные</h1>
<div class="card">
    <h3>Ваш заказ</h3>
    <ul>
        {% for item in cart %}
        <p>
            {{ item.quantity }}x {{item.product.name}}
            <span>{{ item.total_price }} рублей</span>
        </p>
        {% endfor %}
        <p>Всего: {{ cart.get_total_price }} рублей</p>
    </ul>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input id="but2" type="submit" value="Подтвердить"></p>
        {% csrf_token %}
    </form>
</div>
</body>

2 курс 2 семестр/РПМ/django/firstproject/orders/templates/orders/created.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Спасибо за покупку!</title>
    <link rel="stylesheet" href="{% static 'style/main.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/main_ico.ico'%}" type="image/x-icon">
</head>
<body class="aut_body">
<h1 class="text">Спасибо!</h1>
<p class="text">Ваш заказ был успешно принят в обработку. Номер вашего заказа: <strong class="text">{{order.id}}</strong>.</p>
<a href="{% url 'orders:test_send' %}"><button class="newbutton">Отправить чек на почту</button></a>
</body>

2 курс 2 семестр/РПМ/django/firstproject/orders/templates/orders/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Электронный чек</title>
    <link rel="stylesheet" href="{% static 'style/main.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/main_ico.ico'%}" type="image/x-icon">
</head>
<body class="aut_body">
<p class="text">Чек был отправлен на почту nidhappy@mail.ru</p>
</body>